### ISSUE TITLE
Algorithm for shuffle with maximum sequential constraint

### ISSUE THREAD

**Issue by DaniBodor** [ANNUBS/annubes#29]
> > * We need to better define max_sequential usage. Use cases:
> >   
> >   * If ordered is False, simply check for consecutive modalities, and reorder accordingly (implemented now). Implementation can be improved for case limits (e.g., check only for consecutive stimuli, not catches, print a warning if it's not possible to find the "perfect" sequence because of proportions)
> >     
> >     * If ordered is True, maybe we don't want to use max_sequential at all? For now, it is like that. But I see two subcases:
> >       
> >       * If catch_prob > 0 (note that if catch_prob is low you may also have 0 catch anyway). What do we want to do?
> >       * If catch_prob is 0. I would only print a warning if the max_sequential limit is exceeded.
> 
>   * In situations where impossible conditions were given, we should raise an Exception
> 
>   * `max_sequential` should be ignored if `ordered == True`, send warning

A few notes:
- I tested the current implemetation and it doesn't consistently work as intended (even in situations where it is possible). The following minimal code (copied from current implementation) will pretty regularly give an output with 3 sequential values.
```python
import numpy as np

rng = np.random.default_rng(22)

def fy_shuffle(modality_seq: list, max_sequential: int=2) -> list:
    """Shuffle the list using Fisher-Yates algorithm with consecutive constraint."""
    rng.shuffle(modality_seq)
    i = len(modality_seq) - 1
    while i > 0:
        # Picking j can't be fixed, otherwise the algorithm is not random
        # We may want to change this in the future
        j = rng.integers(0, i)
        modality_seq[i], modality_seq[j] = modality_seq[j], modality_seq[i]
        i -= 1
        # Check and fix the consecutive constraint
        count = 1
        while i > 0 and modality_seq[i] == modality_seq[i - 1] and count >= max_sequential:
            i -= 1
    return modality_seq

modality_seq = ['A', 'B', 'C'] * 4

for i in range(10):
    result = fy_shuffle(modality_seq, 2)
    res_str = ''.join(result)
    print(i, res_str)

# OK: 0, 1, 2, 5, 7, 8, 9')
# failing: 3, 4, 6')


> 0 CAACABCBBCAB
> 1 ACABABABCCBC
> 2 CBCBABCABACA
> 3 CCCBBABACAAB
> 4 BBAABACCCABC
> 5 ABCABACBCBCA
> 6 ACCCABACBABB
> 7 AACABBACBCBC
> 8 ACACCBBCABBA
> 9 AACCBBAACCBB
```
- It is not clear how to predefine which settings are strictly speaking possible. This would probably require working out the maths to figure it out. 
- Even after defining parameters that are strictly speaking possible, it is possible to end up in an intermediate state that does not allow for a valid final result. This would either need to be dealt with by "backtracking" or restarting the loop, which can become extremely time-consuming, especially in situations where only a small proportion of outcomes are valid.
- I tried googling for an algorithm to do this consistently (it must have been done in the past), but so far have come up empty. I might just pose the peroblem on StackOverflow or something.

_Originally posted by @DaniBodor in https://github.com/ANNUBS/annubes/issues/26#issuecomment-1937011294_

**Comment by gcroci2** [comment]
Find a trade-off between statistically relevant solution and practicality. We can test real-case scenarios only, not the most difficult ones, we can also think about discarding a trial if it doesn't satisfy the requirement (or logging a warning).

**Comment by gcroci2** [comment]
Okay let's try to find some other algorithm. I can look into that tomorrow. Anyway, I think that 300 trials are way too many, so I'd do the tests using 20-100 trials maximum.

**Comment by DaniBodor** [comment]
Something like this works. 
It would need to be cleaned up a bit to actually put into the code base, but the algorithm works fine. It's probably much slower than a shuffle function (because a random numbers is picked at each repetition), but I doubt that that will be any kind of bottleneck in the final product (It can do a sequence of 100k samples in 1 sec on my laptop).


```python
max_sequential = 4
ratios = {'A': 0.33, 'B': 0.33, 'C': 0.34}
random_seed = 22
n_samples = 100

rng = np.random.default_rng(random_seed)


too_many = max_seq+1
modality_seq = []

def choose_at_random(inp:dict = ratios):
    options = list(inp.keys())
    probabilities = list(inp.values())
    return rng.choice(options, p=probabilities)

for i in range(n_samples):
    modality_seq.append(choose_at_random())

    try:
        while modality_seq[-1:]*too_many == modality_seq[-too_many:]:
            # print(i, modality_seq[-1], modality_seq[-too_many:])
            modality_seq[-1] = choose_at_random()
    except IndexError:  # less than 4 items in list
        pass

res_str = "".join(modality_seq)
print(f"Final sequence: {res_str}")
for x in ratios:
    print(f"Too many repetitions of {x}: {x*too_many in res_str}")
    print(f"True frequency of {x}: {modality_seq.count(x)/n_samples}")


# Final sequence: BAABBCCCABBABAACBABCBAABCBCBCBBBACCCBAABBACCCCBBACCCCBCCBBBBAAABBCABBACBCCCCACAACCCACBBCAAAACACBACAA
# Too many repetitions of A: False
# True frequency of A: 0.31
# Too many repetitions of B: False
# True frequency of B: 0.33
# Too many repetitions of C: False
# True frequency of C: 0.36

```

**Comment by DaniBodor** [comment]
> Something like this works. It would need to be cleaned up a bit to actually put into the code base, but the algorithm works fine. It's probably much slower than a shuffle function (because a random number is picked at each repetition), but I doubt that that will be any kind of bottleneck in the final product (It can do a sequence of 100k samples in 1 sec on my laptop).
> 
> ```python
> max_sequential = 4
> ratios = {'A': 0.33, 'B': 0.33, 'C': 0.34}
> random_seed = 22
> n_samples = 100
> 
> rng = np.random.default_rng(random_seed)
> 
> 
> too_many = max_seq+1
> modality_seq = []
> 
> def choose_at_random(inp:dict = ratios):
>     options = list(inp.keys())
>     probabilities = list(inp.values())
>     return rng.choice(options, p=probabilities)
> 
> for i in range(n_samples):
>     modality_seq.append(choose_at_random())
> 
>     try:
>         while modality_seq[-1:]*too_many == modality_seq[-too_many:]:
>             # print(i, modality_seq[-1], modality_seq[-too_many:])
>             modality_seq[-1] = choose_at_random()
>     except IndexError:  # less than 4 items in list
>         pass
> 
> res_str = "".join(modality_seq)
> print(f"Final sequence: {res_str}")
> for x in ratios:
>     print(f"Too many repetitions of {x}: {x*too_many in res_str}")
>     print(f"True frequency of {x}: {modality_seq.count(x)/n_samples}")
> 
> 
> # Final sequence: BAABBCCCABBABAACBABCBAABCBCBCBBBACCCBAABBACCCCBBACCCCBCCBBBBAAABBCABBACBCCCCACAACCCACBBCAAAACACBACAA
> # Too many repetitions of A: False
> # True frequency of A: 0.31
> # Too many repetitions of B: False
> # True frequency of B: 0.33
> # Too many repetitions of C: False
> # True frequency of C: 0.36
> ```

I will implement this (creating this post so it appears on my to-do list)

**Comment by DaniBodor** [comment]
@gcroci2, while working on this I noticed that in line 369 of the current `_build_trials_seq`, there is already a shuffle step, i.e. before the `if self.shuffle_trials` step of line 371 (see below). The test for this only checks whether `shuffle_trials` is True or False give different results, but not whether the supposedly unshuffled result is actually unshuffled. I've referenced both functions below.

What is line 369 doing here? Is it shuffling catches into each separate block of modalities, which I thought was done in line 361-364. Are these redundant? 
Does that in itself already shuffle the sequence, in which case I can remove it in this PR? 
Something else altogether?

I will also think of a test to ensure that when `shuffle_trials == False` we actually get an unshuffled sequence. My first thought is to test this with `catch_prob=0` to simplify the check, but if you see any problem with that and/or have an immediate idea for a simple way to do it, let me know.

https://github.com/ANNUBS/annubes/blob/dc1e5bf30b7a644d4648fa10b85b13f720e9aa2c/annubes/task.py#L353-L374
https://github.com/ANNUBS/annubes/blob/dc1e5bf30b7a644d4648fa10b85b13f720e9aa2c/tests/test_task.py#L263-L272

**Comment by DaniBodor** [comment]
> @gcroci2, while working on this I noticed that in line 369 of the current `_build_trials_seq`, there is already a shuffle step, i.e. before the `if self.shuffle_trials` step of line 371 (see below). The test for this only checks whether `shuffle_trials` is True or False give different results, but not whether the supposedly unshuffled result is actually unshuffled. I've referenced both functions below.
> 
> What is line 369 doing here? Is it shuffling catches into each separate block of modalities, which I thought was done in line 361-364. Are these redundant? Does that in itself already shuffle the sequence, in which case I can remove it in this PR? Something else altogether?

OK, I think I got it:
- line 359 randomly chooses a true ratio of the different modalities
- lines 361-364 randomly chooses a true ratio between catch and each modality
- line 369 shuffles catches into the sequence of modalities
- line 371 shuffles the entire thing
(i.e. no redundancy anywhere)

Is that it? If so, I will add some comments into the code to clarify.

**Comment by gcroci2** [comment]
> What is line 369 doing here? Is it shuffling catches into each separate block of modalities, which I thought was done in line 361-364. Are these redundant? Does that in itself already shuffle the sequence, in which case I can remove it in this PR? Something else altogether?

- Lines 361-364. They create a dictionary containing the possible scenarios as keys (e.g., 'a', 'v') and for each scenario the value is an array containing the number of times that within a scenario you actually have that scenario, and the number of times that you have a catch, randomly determining it according to the probabilities of the catch. So if you have a session which is `{'a': 0.5, 'v':0.5}`, a `catch_prob` of 0.5, and `ntrials` of 20 for example, a possible `session_in_samples` can be `{'a': array([6, 5]), 'v': array([4, 5])}`, with the first element of each key's value being the number of trials marked as the key, and the second element being the number of trials marked as 'catch'. This way you are sure that you respect the probabilities, in this case 0.5 catch prob (which are 10) and the rest either 'a' or 'v', both present ~50% of the time in the remaining trials (6 and 4, respectively). If catch_prob is 0, the second element of the arrays will be always 0. You still have no information about the order of the modalities in the sequence, but only their frequency. You still need to determine the sequence at this point. 
- Line 369: at this point you actually have a sequence of a scenarios (e.g., 'a' + 'catch'), and you shuffle them to have catch trials randomly placed within the specific scenario's sequence. 
- Line 371: shuffles the entire sequence if `shuffle_trials` is True, so only if the user doesn't want to keep the order of the scenarios as indicated in `session` (in the above example, keeping the order would be: first 'a', then 'v', with random 'catch' scattered across the entire sequence).

> I will also think of a test to ensure that when `shuffle_trials == False` we actually get an unshuffled sequence. My first thought is to test this with `catch_prob=0` to simplify the check, but if you see any problem with that and/or have an immediate idea for a simple way to do it, let me know.

Fine for me :)
