### ISSUE TITLE
Fixation as independent signal

### ISSUE THREAD

**Issue by DaniBodor** [ANNUBS/annubes#30]
> > * Now value_fixation can be set by the user, but there are many possible ways to implement this. As it is now, the user can set a value for the fixation period, which then will be set for each stimulus present, and scaled according to the stimuli intensity values, if scaling is True. Check if this implementation is satisfying.
> 
> Should be coded as an independent signal. With its own duration, intensity, etc.

Is this different from what we are currently doing? If so, I think it's best to open a separate issue for this.

_Originally posted by @DaniBodor in https://github.com/ANNUBS/annubes/issues/26#issuecomment-1937002416_

**Comment by gcroci2** [comment]
We've decided to implement the functionalities originally planned for the `annubes` package within the [NeuroGym](https://github.com/neurogym/neurogym) package instead, which represents the current state-of-the-art. There, fixation is already used as an independent signal.
