### ISSUE TITLE
Switch docs to Mkdocs

### ISSUE THREAD

**Issue by gcroci2** [ANNUBS/annubes#45]
_Inspired by NPLinker ([PR #218](https://github.com/NPLinker/nplinker/pull/218))_

[MkDocs](https://www.mkdocs.org/) is going to be used to build doc website. Reasons:

- Even if Sphinx can support markdown with the help of [myst_parser](https://myst-parser.readthedocs.io/en/latest/), markdown support is limited with Sphinx.
- Mkdocs has simpler setup
- Mkdocs have more fancy and modern looking (with the theme [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)) than Sphinx

MKDocs useful links:
- The engine https://www.mkdocs.org/
- The all-in-one theme https://squidfunk.github.io/mkdocs-material/
- Plugin for docstrings https://mkdocstrings.github.io/
- [Settings](https://github.com/NPLinker/nplinker/blob/dev/mkdocs.yml) used in NPLinker

**Comment by CunliangGeng** [comment]
Reason 4: mkdocs uses github pages as the website so you don't need [readthedocs.com](https://about.readthedocs.com/) any more.

To manage multiple versions of docs on github pages, this tool is helpful  https://github.com/jimporter/mike
