### ISSUE TITLE
refactor: improve the plotting

### ISSUE THREAD

**Issue by gcroci2** [ANNUBS/annubes#89]
![image](https://github.com/ANNUBS/annubes/assets/55382553/413246c6-28e2-4769-aceb-234ecdafc135)

- X axis should have some values
- X axis should be cut at the max value present in the trials

**Comment by gcroci2** [comment]
Other suggestions? @jfmejias @DaniBodor

**Comment by DaniBodor** [comment]
- Y-axis label and units (even if AU). 
- the dashed vertical line should be in the legend (or labeled in another fashion)
- Ensure color scheme is color-blind friendly (haven't checked the current one).
- Given that there are really just two possible values (apart from noise) and multiple signals that overlay each other, it can be difficult to see which ones are at which value. I don't have a great idea of how to improve this, but it could be something to keep in the back of our minds.

**Comment by gcroci2** [comment]
We've decided to implement the functionalities originally planned for the `annubes` package within the [NeuroGym](https://github.com/neurogym/neurogym) package instead, which represents the current state-of-the-art.
